#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---
- name: add required gpg key
  apt_key:
    keyserver: "hkp://pgp.mit.edu:80"
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    state: present

- name: add apt sources
  lineinfile:
    dest: "/etc/apt/sources.list.d/docker.list"
    line: "deb https://apt.dockerproject.org/repo ubuntu-{{ ubuntu_release }} main"
    state: present
    create: yes
  notify:
    - update apt cache

- name: install Docker engine packages
  apt: name="docker-engine" state=present

- name: install docker-py python module
  pip: name={{ item }} state=latest
  with_items:
    - docker-py

- name: start and enable Docker at boot
  service: name=docker enabled=yes state=started

- name: add docker options to the deamon run
  lineinfile:
    dest: "{{ docker_env_file }}"
    regexp: "^DOCKER_OPTS="
    line: 'DOCKER_OPTS="{{ docker_opts }}"'
    state: present
  notify:
    - restart docker
  when: docker_opts is defined
